#!/bin/bash

clean_file(){
    if [[ -f ${1} ]]; then
        rm ${1}
    fi
    touch ${1}
}

mandle_MPI=/home/kieran/coding/Cuda-mandlebrot/build_MPI/mandle
mandle_CUDA=/home/kieran/coding/Cuda-mandlebrot/build_CUDA/mandle

log_CUDA=${PWD}/cuda_log.txt
log_MPI=${PWD}/MPI_log.txt

# Initially lets run at some different resolutions
base=$PWD

scales=(100 200 500 1000 2000 3000)

clean_file ${log_CUDA}
clean_file ${log_MPI}


for res in ${scales[@]}; do
    cd ${base}/${res}
    export RES=$(basename $PWD)
    envsubst < ../config.json > config.json

    # Cuda
    time=$(${mandle_CUDA} -i config.json -t 1024 -b 1024)
    echo "${RES} ${time}" >> ${log_CUDA}

    # MPI
    time=$(mpirun --mca btl self,vader -n 6 ${mandle_MPI} -i config.json)
    echo "${RES} ${time}" >> ${log_MPI}
done